apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  namespace: goapp
spec:
  selector:
    matchLabels:
      app: goapp
  replicas: 2
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: dmassaro/argocd-poc:v2
        resources:
          limits:
            memory: "64Mi"
            cpu: "125m"
        ports:
        - containerPort: 8080
