apiVersion: v1
kind: Service
metadata:
  labels:
    run: goapp
  name: goapp
  namespace: goapp
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30008
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: goapp
  sessionAffinity: None
  type: NodePort
