apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.1.0
  dependsOn:
  - name: monitoring
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: ingress-nginx-internal
  storageNamespace: ingress-nginx-internal
  targetNamespace: ingress-nginx-internal
  values:
    controller:
      admissionWebhooks:
        # enable after install in order to avoid ingress deadlock
        enabled: false
      ingressClassResource:
        name: nginx-internal
        enabled: true
        default: true
        controllerValue: "k8s.io/nginx-internal"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: role
                operator: In
                values:
                - infra
      resources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi

      #priorityClassName: high-priority

      dnsPolicy: ClusterFirstWithHostNet

      extraArgs:
        enable-ssl-passthrough: "false"

      config:
        #proxy-protocol: "True"
        #real-ip-header: proxy_protocol
        #set-real-ip-from: X.X.X.X

      kind: Deployment

      replicaCount: 2

      autoscaling:
        enabled: false
        minReplicas: 2
        maxReplicas: 30
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

      podSecurityPolicy:
        enabled: true

      service:
        enabled: true
        type: LoadBalancer
        #loadBalancerIP: 1.1.1.1

        annotations:
          # aks
          #service.beta.kubernetes.io/azure-load-balancer-internal: false
          # eks
          #service.beta.kubernetes.io/aws-load-balancer-internal: true
          service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal

      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: infra
      - effect: NoSchedule
        key: CriticalAddonsOnly

    defaultBackend:
      enabled: true
      nodeSelector:
        role: infra

      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 20m
          memory: 32Mi

      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: infra
      - effect: NoSchedule
        key: CriticalAddonsOnly

    rbac:
      create: true

    serviceAccount:
      create: true